FROM python:3.9-slim 

RUN apt-get update
RUN apt-get install -y --no-install-recommends build-essential gcc libpq-dev
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install wheel

COPY ./aggregator/ ./aggregator
WORKDIR /aggregator

RUN apt-get update
RUN apt-get install -y --no-install-recommends build-essential gcc libpq-dev

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]