# syntax=docker/dockerfile:1
FROM node:16-alpine3.14
ENV NODE_ENV=production
WORKDIR /app

COPY package-lock.json .
COPY package.json .

RUN npm install --production
COPY . .
EXPOSE 3000
CMD [ "node", "app.js" ]
