# syntax=docker/dockerfile:1
FROM node:16-alpine3.14
ENV NODE_ENV=production
WORKDIR /app

RUN apk --no-cache add curl

COPY templates /app/templates
COPY app.js /app/app.js
COPY public /app/public
COPY migrations /app/migrations
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

RUN npm install --production
EXPOSE 3000